FROM rabbitmq:3.7.5-management

LABEL maintainer="vashchukmaksim@gmail.com"

ADD rabbitmq-dev.config /etc/rabbitmq/rabbitmq.config
ADD definitions-dev.json /etc/rabbitmq/definitions.json

RUN chown rabbitmq:rabbitmq /etc/rabbitmq/rabbitmq.config /etc/rabbitmq/definitions.json

CMD ["rabbitmq-server"]
